In [6]:
import pandas as pd

In [8]:
print(pd.__version__)

1.4.4

In [17]:
df_test_data = pd.read_csv('CsvFiles/成績一覧表.csv',encoding='utf-8',)

In [19]:
type(df_test_data)

pandas.core.frame.DataFrame

In [65]:
pd.set_option('display.max_rows',5) #最大表示列

In [66]:
df_test_data
#(データがえぐいほどある時元から省略されるからそう言う時はmax_rowsを拡張でき､全表示できる)

        試験名    担任  学年  組   №     氏名  国語  数学  理科  社会  英語   合計
0   1学期中間試験  山田　諭   3  1   1  浅野　麻耶  84  74  65  77  78  378
1   1学期中間試験  山田　諭   3  1   2  井戸　弘樹  55  75  45  58  98  331
..      ...   ...  .. ..  ..    ...  ..  ..  ..  ..  ..  ...
43  1学期中間試験  山田　諭   3  1  44  矢部　由香  60  44  75  88  57  324
44  1学期中間試験  山田　諭   3  1  45  横山　理恵  57  56  65  94  95  367

[45 rows x 12 columns]

In [64]:
df_test_data

        試験名    担任  学年  組   №      氏名  国語  数学  理科  社会  英語   合計
0   1学期中間試験  山田　諭   3  1   1   浅野　麻耶  84  74  65  77  78  378
1   1学期中間試験  山田　諭   3  1   2   井戸　弘樹  55  75  45  58  98  331
2   1学期中間試験  山田　諭   3  1   3    岡　和重  84  55  75  48  44  306
3   1学期中間試験  山田　諭   3  1   4    岡本　昭  75  68  75  54  65  337
4   1学期中間試験  山田　諭   3  1   5   小川　雅行  68  64  85  65  58  340
5   1学期中間試験  山田　諭   3  1   6    斉藤　敦  57  85  65  85  87  379
6   1学期中間試験  山田　諭   3  1   7   佐野　俊一  95  75  54  77  54  355
7   1学期中間試験  山田　諭   3  1   8    白浜　誠  84  45  68  68  88  353
8   1学期中間試験  山田　諭   3  1   9   田中　賢治  75  68  75  54  65  337
9   1学期中間試験  山田　諭   3  1  10   中村　晴彦  84  58  95  85  87  409
10  1学期中間試験  山田　諭   3  1  11    原　文雄  66  75  77  95  95  408
11  1学期中間試験  山田　諭   3  1  12   光中　弘樹  54  77  58  44  65  298
12  1学期中間試験  山田　諭   3  1  13   安原　大輔  75  84  45  58  88  350
13  1学期中間試験  山田　諭   3  1  14    柵原　鉄  95  91  86  57  77  406
14  1学期中間試験  山田　諭   3  1  15   山田　智一  85  82  82  87  95  431
15  1学期中間試験  山田　諭   3  1  16   雪森　寿之  98  45  70  95  45  353
16  1学期中間試験  山田　諭   3  1  17    渡邊　聡  54  77  58  44  65  298
17  1学期中間試験  山田　諭   3  1  18  秋田　真由子  45  65  70  88  86  354
18  1学期中間試験  山田　諭   3  1  19  伊藤　裕美子  78  88  60  35  90  351
19  1学期中間試験  山田　諭   3  1  20   大波　恵子  65  57  56  45  85  308
20  1学期中間試験  山田　諭   3  1  21   小川　美和  83  84  85  65  75  392
21  1学期中間試験  山田　諭   3  1  22   小林　弘子  82  95  62  55  84  378
22  1学期中間試験  山田　諭   3  1  23   近藤　智美  75  84  92  75  35  361
23  1学期中間試験  山田　諭   3  1  24   後藤　悦子  81  75  75  85  65  381
24  1学期中間試験  山田　諭   3  1  25   佐伯　博子  59  77  77  94  85  392
25  1学期中間試験  山田　諭   3  1  26  佐々木　千尋  88  56  85  44  75  348
26  1学期中間試験  山田　諭   3  1  27   澤田　綾子  79  48  65  56  44  292
27  1学期中間試験  山田　諭   3  1  28   高木　博子  81  56  84  85  57  363
28  1学期中間試験  山田　諭   3  1  29   田中　典子  72  85  75  55  95  382
29  1学期中間試験  山田　諭   3  1  30   田中　久子  72  85  75  55  95  382
30  1学期中間試験  山田　諭   3  1  31   田辺　香織  83  45  65  67  80  340
31  1学期中間試験  山田　諭   3  1  32   戸倉　由香  64  84  35  84  48  315
32  1学期中間試験  山田　諭   3  1  33   長瀬　千恵  58  75  55  99  97  384
33  1学期中間試験  山田　諭   3  1  34   難波　優子  75  65  75  57  55  327
34  1学期中間試験  山田　諭   3  1  35    原　萌子  95  99  89  88  97  468
35  1学期中間試験  山田　諭   3  1  36  藤波　みずき  75  57  45  77  65  319
36  1学期中間試験  山田　諭   3  1  37  堀部　みちる  88  48  85  56  84  361
37  1学期中間試験  山田　諭   3  1  38   松崎　康代  65  57  65  90  57  334
38  1学期中間試験  山田　諭   3  1  39   松本　佳子  75  62  85  85  76  383
39  1学期中間試験  山田　諭   3  1  40  三村　由紀子  75  82  77  65  84  383
40  1学期中間試験  山田　諭   3  1  41  宮口　由紀子  44  45  76  80  50  295
41  1学期中間試験  山田　諭   3  1  42   三宅　京子  85  76  45  75  95  376
42  1学期中間試験  山田　諭   3  1  43   薮野　朋子  90  85  88  68  88  419
43  1学期中間試験  山田　諭   3  1  44   矢部　由香  60  44  75  88  57  324
44  1学期中間試験  山田　諭   3  1  45   横山　理恵  57  56  65  94  95  367

In [63]:
pd.reset_option('display.max_rows') #上でセットしたオプションをリセットする

In [67]:
df_test_data.head() #デフォルトが５

       試験名    担任  学年  組  №     氏名  国語  数学  理科  社会  英語   合計
0  1学期中間試験  山田　諭   3  1  1  浅野　麻耶  84  74  65  77  78  378
1  1学期中間試験  山田　諭   3  1  2  井戸　弘樹  55  75  45  58  98  331
2  1学期中間試験  山田　諭   3  1  3   岡　和重  84  55  75  48  44  306
3  1学期中間試験  山田　諭   3  1  4   岡本　昭  75  68  75  54  65  337
4  1学期中間試験  山田　諭   3  1  5  小川　雅行  68  64  85  65  58  340

In [72]:
pd.set_option('display.max_rows',50)
df_test_data.head(10)

       試験名    担任  学年  組   №     氏名  国語  数学  理科  社会  英語   合計
0  1学期中間試験  山田　諭   3  1   1  浅野　麻耶  84  74  65  77  78  378
1  1学期中間試験  山田　諭   3  1   2  井戸　弘樹  55  75  45  58  98  331
2  1学期中間試験  山田　諭   3  1   3   岡　和重  84  55  75  48  44  306
3  1学期中間試験  山田　諭   3  1   4   岡本　昭  75  68  75  54  65  337
4  1学期中間試験  山田　諭   3  1   5  小川　雅行  68  64  85  65  58  340
5  1学期中間試験  山田　諭   3  1   6   斉藤　敦  57  85  65  85  87  379
6  1学期中間試験  山田　諭   3  1   7  佐野　俊一  95  75  54  77  54  355
7  1学期中間試験  山田　諭   3  1   8   白浜　誠  84  45  68  68  88  353
8  1学期中間試験  山田　諭   3  1   9  田中　賢治  75  68  75  54  65  337
9  1学期中間試験  山田　諭   3  1  10  中村　晴彦  84  58  95  85  87  409

In [74]:
df_test_data.tail(10) #後ろから10行表示

        試験名    担任  学年  組   №      氏名  国語  数学  理科  社会  英語   合計
35  1学期中間試験  山田　諭   3  1  36  藤波　みずき  75  57  45  77  65  319
36  1学期中間試験  山田　諭   3  1  37  堀部　みちる  88  48  85  56  84  361
37  1学期中間試験  山田　諭   3  1  38   松崎　康代  65  57  65  90  57  334
38  1学期中間試験  山田　諭   3  1  39   松本　佳子  75  62  85  85  76  383
39  1学期中間試験  山田　諭   3  1  40  三村　由紀子  75  82  77  65  84  383
40  1学期中間試験  山田　諭   3  1  41  宮口　由紀子  44  45  76  80  50  295
41  1学期中間試験  山田　諭   3  1  42   三宅　京子  85  76  45  75  95  376
42  1学期中間試験  山田　諭   3  1  43   薮野　朋子  90  85  88  68  88  419
43  1学期中間試験  山田　諭   3  1  44   矢部　由香  60  44  75  88  57  324
44  1学期中間試験  山田　諭   3  1  45   横山　理恵  57  56  65  94  95  367

In [76]:
a = df_test_data #いちいち書くのめんどいからこっから aでやる
a.sample(10) #ランダムでどこかの10行取ってくる

        試験名    担任  学年  組   №      氏名  国語  数学  理科  社会  英語   合計
25  1学期中間試験  山田　諭   3  1  26  佐々木　千尋  88  56  85  44  75  348
30  1学期中間試験  山田　諭   3  1  31   田辺　香織  83  45  65  67  80  340
10  1学期中間試験  山田　諭   3  1  11    原　文雄  66  75  77  95  95  408
42  1学期中間試験  山田　諭   3  1  43   薮野　朋子  90  85  88  68  88  419
5   1学期中間試験  山田　諭   3  1   6    斉藤　敦  57  85  65  85  87  379
36  1学期中間試験  山田　諭   3  1  37  堀部　みちる  88  48  85  56  84  361
29  1学期中間試験  山田　諭   3  1  30   田中　久子  72  85  75  55  95  382
22  1学期中間試験  山田　諭   3  1  23   近藤　智美  75  84  92  75  35  361
16  1学期中間試験  山田　諭   3  1  17    渡邊　聡  54  77  58  44  65  298
3   1学期中間試験  山田　諭   3  1   4    岡本　昭  75  68  75  54  65  337

In [87]:
a.info()  #表のカラムごとの情報

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   試験名     45 non-null     object
 1   担任      45 non-null     object
 2   学年      45 non-null     int64
 3   組       45 non-null     int64
 4   №       45 non-null     int64
 5   氏名      45 non-null     object
 6   国語      45 non-null     int64
 7   数学      45 non-null     int64
 8   理科      45 non-null     int64
 9   社会      45 non-null     int64
 10  英語      45 non-null     int64
 11  合計      45 non-null     int64
dtypes: int64(9), object(3)
memory usage: 4.3+ KB

In [79]:
a.describe()

,学年,組,№,国語,数学,理科,社会,英語,合計
count,45.0,45.0,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
mean,3.0,1.0,23.000000,74.155556,69.622222,70.311111,70.244444,74.511111,358.844444
std,0.0,0.0,13.133926,13.557882,15.290058,14.223576,17.306273,17.829524,38.573988
min,3.0,1.0,1.000000,44.000000,44.000000,35.000000,35.000000,35.000000,292.000000
25%,3.0,1.0,12.000000,65.000000,57.000000,62.000000,56.000000,58.000000,334.000000
50%,3.0,1.0,23.000000,75.000000,75.000000,75.000000,68.000000,78.000000,355.000000
75%,3.0,1.0,34.000000,84.000000,84.000000,82.000000,85.000000,88.000000,382.000000
max,3.0,1.0,45.000000,98.000000,99.000000,95.000000,99.000000,98.000000,468.000000

In [80]:
a.describe().round(0)

         学年     組     №    国語    数学    理科    社会    英語     合計
count  45.0  45.0  45.0  45.0  45.0  45.0  45.0  45.0   45.0
mean    3.0   1.0  23.0  74.0  70.0  70.0  70.0  75.0  359.0
std     0.0   0.0  13.0  14.0  15.0  14.0  17.0  18.0   39.0
min     3.0   1.0   1.0  44.0  44.0  35.0  35.0  35.0  292.0
25%     3.0   1.0  12.0  65.0  57.0  62.0  56.0  58.0  334.0
50%     3.0   1.0  23.0  75.0  75.0  75.0  68.0  78.0  355.0
75%     3.0   1.0  34.0  84.0  84.0  82.0  85.0  88.0  382.0
max     3.0   1.0  45.0  98.0  99.0  95.0  99.0  98.0  468.0

In [88]:
a.groupby(by='組').mean().round(0)

    学年     №    国語    数学    理科    社会    英語     合計
組
1  3.0  23.0  74.0  70.0  70.0  70.0  75.0  359.0